"""Build the static SPYA redesign. Standard-library Python 3.9+."""
from pathlib import Path
from html import escape as e
from datetime import datetime
from zoneinfo import ZoneInfo
import json
R = Path(__file__).resolve().parents[1]
D = json.loads((R/'data/site.json').read_text()); S = D['sports']
A = json.loads((R/'data/assets.json').read_text())
NOW = datetime.now(ZoneInfo('America/New_York'))
def asset(key):
    a=A[key]
    return a['local'] if (R/a['local']).is_file() else a['url']
def picture(key,alt,cls='',eager=False):
    return f'<img class="{cls}" src="{e(asset(key))}" alt="{e(alt)}" loading="{"eager" if eager else "lazy"}" decoding="async">'
def link(label,url,cls=''):return f'<a class="{cls}" href="{e(url)}">{e(label)}</a>'
def accordion(title,html):return f'<details><summary>{e(title)}</summary><div class="disclosure-body">{html}</div></details>'
def intro(label,title,text):return f'<section class="page-intro container"><p class="eyebrow">{e(label)}</p><h1>{e(title)}</h1><p class="lead">{e(text)}</p></section>'
def shell(title,body,active=''):
    items=[('sports','Sports'),('registration','Registration'),('resources','Families'),('community','Community'),('about','About')]
    nav=''.join(f'<a href="{k}.html"'+(' aria-current="page"' if active==k else '')+f'>{t}</a>' for k,t in items)
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | SPYA</title><meta name="description" content="{e(title)} — South Parkland Youth Association sports, family resources and community in Allentown, Pennsylvania."><link rel="icon" href="{e(asset('logo'))}"><link rel="stylesheet" href="css/styles.css"><script src="js/app.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header><div class="container header-inner"><a class="brand" href="index.html" aria-label="SPYA Home">{picture('logo','',eager=True)}<span>South Parkland<br>Youth Association</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav">Menu</button><nav id="primary-nav" class="nav" aria-label="Main Navigation">{nav}</nav></div></header><main id="main">{body}</main><footer><div class="container footer-inner"><p><strong>SPYA</strong><br>360 Grange Road · Allentown, PA 18069</p><p>Teamwork. Sportsmanship. Community.</p></div></footer></body></html>'''
def write(name,body): (R/name).write_text(body,encoding='utf-8')
# Only one promotion and one entry link; no duplicate on a program page.
raffle=''
if NOW < datetime(2026,11,8,tzinfo=ZoneInfo('America/New_York')):
    raffle=f'''<section class="feature container" data-expires="2026-11-08T00:00:00-05:00"><div class="feature-label"><span class="eyebrow">Community Fundraiser</span><span class="date-chip">Drawing · November 8, 2026</span></div><div class="feature-content"><h2>Eagles Ticket Raffle</h2><p>Two winners. Four Eagles tickets each. View the flyer for prize details and the TeamSnap form for entry information.</p>{link('View Raffle Entry','https://go.teamsnap.com/forms/526605','button')}<p class="small">TeamSnap sign-in may be required. Entry availability must be confirmed in the form.</p>{accordion('View the Raffle Flyer',picture('raffle','SPYA Eagles ticket raffle flyer. Two winners receive four tickets each in Section 107, Row 17. Drawing November 8. Consult TeamSnap for full entry terms.','poster'))}</div></section>'''
home=f'''<section class="home-hero container"><div class="hero-copy"><p class="eyebrow">Allentown, Pennsylvania</p><h1>A Place to Play.<br><span>A Team to Belong To.</span></h1><p class="lead">Youth sports that build skills, friendships, and confidence.</p></div><figure class="hero-photo">{picture('legion','South Parkland’s 2023 Senior Legion championship team',eager=True)}<figcaption>Senior Legion Baseball · 2023 Champions</figcaption></figure></section>{raffle}<section class="mission"><div class="container mission-inner"><h2>More Than a Game</h2><p>Powered by local volunteers, our nine sports programs give young people a place to learn teamwork, build character, and enjoy playing together.</p></div></section>'''
write('index.html',shell('Home',home))
cards=''.join(f'<a class="sport-card" href="{s["slug"]}.html" data-sport="{e(s["name"]+" "+s["season"])}"><span class="sport-number">{i:02d}</span><h2>{e(s["name"])}</h2><p>{e(s["summary"])}</p><span class="sport-arrow" aria-hidden="true">↗</span></a>' for i,s in enumerate(S,1))
write('sports.html',shell('Sports',intro('Our Programs','Find Their Game','Choose a sport for program details, equipment guidance, and a direct contact.')+f'<section class="section container"><div class="toolbar"><label for="sport-search">Search sports<input id="sport-search" type="search" placeholder="Sport or season" data-search></label><span data-count aria-live="polite">9 sports</span></div><div class="sports-grid">{cards}</div><p data-empty hidden>No matching sports. Try another search.</p></section>','sports'))
for s in S:
    programs=''.join(accordion(t,f'<p>{e(p)}</p>') for t,p in s['programs'])
    extra=''
    if s['slug']=='nfl-flag' and NOW < datetime(2026,10,26,tzinfo=ZoneInfo('America/New_York')):
        extra='<div data-expires="2026-10-26T00:00:00-04:00">'+accordion('Fall 2026 Season','<p>The published season runs August 22–October 25, 2026. Use team communications for individual game times and changes.</p>')+'</div>'
    if s['slug']=='football':
        extra=accordion('League Information',f'<p>{link("EPYFL Bylaws","https://epyfl.org/about_laws.asp")}</p><p>{link("EPYFL Standings","https://epyfl.org/standings.asp")}</p>')
    if s['slug']=='soccer':extra=accordion('Player Code of Conduct',link('Soccer Code of Conduct (PDF)','https://spya.org/wp-content/uploads/sites/1365/2026/04/South-Parkland-Soccer-Code-of-Conduct-2021.pdf'))
    if s['slug']=='softball':extra=accordion('Field Location',picture('softball-map','SPYA’s published map of softball fields at Springhouse Middle School','field-map'))
    if s['slug']=='baseball':
        extra=accordion('League Resources',f'<p>{link("Parkland Youth League","http://www.pylbaseball.com/")}</p><p>{link("PYL Rules and Equipment","https://drive.google.com/file/d/1wLy3SH-0ooKumfzA3wW8o07OoVCZEM-n/view")}</p><p>{link("Lehigh Valley League","https://www.leaguelineup.com/welcome.asp?url=lvlbl")}</p><p>{link("Connie Mack League","https://www.leaguelineup.com/welcome.asp?url=lvcm")}</p>')
        extra+=accordion('Baseball Program Sponsors','<p>Sponsor recognition from the baseball program.</p><div class="sponsor-grid">'+''.join(picture(k,A[k]['alt']) for k in A if k.startswith('sponsor-'))+'</div>')
    body=intro('Sports',s['name'],s['summary'])+f'''<section class="section container detail-grid"><div><h2>Program Overview</h2>{programs}{extra}</div><aside class="contact-panel"><span class="eyebrow">Program Contact</span><h2>Let’s Talk {e(s['name'])}</h2><p>Ask about eligibility, team placement, equipment, and the next season.</p>{link(s['email'],'mailto:'+s['email'],'email')}<p class="small">Find current form information in Registration, in the main menu.</p></aside></section>'''
    write(s['slug']+'.html',shell(s['name'],body,'sports'))
# One row per sport; direct links retained without asserting accepting registrations.
closed={'nfl-flag':'Fall 2026 registration closed September 3.','soccer':'Fall 2026 registration closed September 12.','softball':'Fall 2026 registration closed September 1.'}
forms={'cheer':[('Cheer Form','521215')],'field-hockey':[('Field Hockey Form','522311')],'football':[('Flag Form','523764'),('Junior Pee Wee Form','523762'),('Pee Wee Form','523742'),('Junior Varsity Form','523761'),('Varsity Form','523741')]}
rows=''
for s in S:
    slug=s['slug']; controls=''
    if slug in closed:
        state='Closed';desc=closed[slug];controls=link('Ask About the Next Season','mailto:'+s['email'])
    elif slug in forms:
        state='Check With Program';desc='Current form availability is unconfirmed.'
        if slug=='football':controls=accordion('Choose a Football Division',''.join('<p>'+link(label,'https://go.teamsnap.com/forms/'+fid)+'</p>' for label,fid in forms[slug]))
        else:controls=link(forms[slug][0][0],'https://go.teamsnap.com/forms/'+forms[slug][0][1])
    else:
        state='Contact Program';desc='A current registration window has not been verified.';controls=link('Request Registration Details','mailto:'+s['email'])
    rows+=f'<article class="registration-row"><h2>{e(s["name"])}</h2><div><span class="status">{state}</span><p>{desc}</p></div><div>{controls}</div></article>'
body=intro('Join a Team','Registration','Choose your program below. Registration takes place in TeamSnap; signing in does not guarantee that a form is accepting players.')+f'<section class="section container"><p class="review-note">Form review: September 16, 2026. Availability can change.</p><div class="registration-list">{rows}</div><p class="small">Before paying, confirm eligibility, fees, equipment, and the applicable refund terms. Financial assistance documents are in Families.</p></section>'
write('registration.html',shell('Registration',body,'registration'))
policy='https://spya.org/wp-content/uploads/sites/1365/2026/09/SPYA-Financial-Assistance-Policy-revised-September-2026.pdf'
application='https://spya.org/wp-content/uploads/sites/1365/2026/07/SPYA-Financial-Assistance-Application-1.pdf'
bylaws='https://spya.org/wp-content/uploads/sites/1365/2020/04/SPYA-BY-LAWS-06-10-2019.pdf'
body=intro('For Families','Ready for the Season','Practical information, financial support, and ways to lend a hand.')+f'''<section class="section container resource-sections"><article id="assistance"><div><p class="eyebrow">Financial Assistance</p><h2>Help With Participation</h2></div><div><p>Need help with registration costs? Review the financial assistance policy for eligibility, required documents, and application deadlines.</p>{link('FinancialAid@spya.org','mailto:FinancialAid@spya.org','email')}<div class="document-list">{link('Assistance Policy · September 2026 (PDF)',policy)}{link('Assistance Application (PDF)',application)}</div></div></article><article id="volunteer"><div><p class="eyebrow">Volunteering</p><h2>Make Their Season Possible</h2></div><div><p>Volunteer opportunities include coaching, team management, field preparation, concessions, fundraising, and equipment support. Tell your program commissioner how you would like to help.</p><p>Sport contact details are on each program page. Ask about training, clearances, and any volunteer fee arrangements before the season.</p></div></article><article><div><p class="eyebrow">Common Questions</p><h2>Before You Begin</h2></div><div>{accordion('Are Tryouts Required?','<p>Selection varies by sport and division. Some teams hold tryouts; others use evaluations to balance teams. Confirm the process for your child’s program.</p>')}{accordion('What Equipment Will We Need?','<p>Check your program’s equipment list before buying anything. Some programs provide or loan equipment; availability and deposits vary.</p>')}{accordion('Where Will We Play?','<p>Locations vary by sport and team. Use your team’s communications for practice locations and last-minute changes.</p>')}{accordion('How Do Fees and Refunds Work?','<p>Review the terms for your sport before registering. Travel programs may have additional costs, and refund exceptions differ by program. Ask the commissioner about your circumstances.</p>')}{accordion('Can I Get Help With Online Registration?','<p>Contact your sport commissioner if you cannot complete the online process. Each program page lists the appropriate email address.</p>')}</div></article><article><div><p class="eyebrow">Association Documents</p><h2>Governance</h2></div><div>{link('SPYA Bylaws · June 2019 (PDF)',bylaws)}<p class="small">Contact the secretary about amendments to this edition.</p></div></article></section>'''
write('resources.html',shell('Family Resources',body,'resources'))
# Community contains history, not outdated enrollment announcements.
champs=[('Bulls','15U'),('Dolphins','13U (A)'),('Venom','13U (B)'),('Wolverines','11U'),('Venom','9U'),('Fluffy Unicorns','7U (A)'),('Eagles','7U (B)')]
gallery=''.join(f'<figure>{picture("flag-"+str(i),name+" — Spring 2026 "+division+" Champions")}<figcaption><strong>{name}</strong><span>{division} · Spring 2026</span></figcaption></figure>' for i,(name,division) in enumerate(champs,1))
body=intro('Community','On and Off the Field','Celebrating our teams, volunteers, and shared achievements.')+f'''<section class="section container"><article class="calendar-callout"><div><h2>Association Calendar</h2><p>Plan ahead with the association calendar. Check team communications for last-minute changes.</p></div>{link('View Calendar','calendar.html','button')}</article><div class="section-heading"><p class="eyebrow">Team Achievements</p><h2>Spring 2026 NFL Flag Champions</h2><p>Celebrating the teams from the completed spring season.</p></div><div class="photo-grid">{gallery}</div><div class="history-section">{accordion('Baseball and Lacrosse History',f'<h3>2023 Senior Legion Champions</h3><p>Our Senior Legion team won the Lehigh Valley Legion regular season and playoff championships.</p><h3>Lacrosse Championship Teams</h3><p>2022 Lehigh Valley Box League: 7/8 and 3/4 divisions. 2021 LVYLL: 7/8 division. 2021 Box League: 7/8 and 5/6 divisions. 2020 and 2019 Box League: 5/6 division. 2018 LVYLL: 3/4 division.</p>{picture("lacrosse-champs","SPYA 7/8 team — 2022 Lehigh Valley Box League champions","history-photo")}<h3>Lacrosse Hall of Fame</h3><p>Coach Sean Gill founded our lacrosse program in 2014.</p>')}</div><div class="social-links"><h2>Follow SPYA</h2>{link('Instagram','https://www.instagram.com/spyasports/')}{link('Facebook','https://www.facebook.com/SouthParklandYouthAssociation/')}</div></section>'''
write('community.html',shell('Community',body,'community'))
calendar='https://calendar.google.com/calendar/embed?ctz=America/New_York&src=spyatrojancal@gmail.com'
body=intro('Community','Association Calendar','Times are shown in Eastern Time. Check team communications for schedule changes.')+f'<section class="section container"><iframe class="calendar-frame" title="SPYA Association Calendar" src="{e(calendar)}" loading="lazy"></iframe><p class="small">If the calendar does not load, {link("open it in Google Calendar",calendar)}.</p></section>'
write('calendar.html',shell('Calendar',body,'community'))
roles=[('President','president@spya.org'),('Vice President','vicepresident@spya.org'),('Treasurer','treasurer@spya.org'),('Secretary','secretary@spya.org'),('Social Media','socialmedia@spya.org'),('Website and Online Registration','webmaster@spya.org'),('Website Support','shedlock@spya.org')]
contacts=''.join(f'<article class="contact"><h3>{role}</h3>{link(email,"mailto:"+email)}</article>' for role,email in roles)
body=intro('About','Local Teams. Shared Purpose.','A nonprofit, volunteer-run youth sports association in Allentown, Pennsylvania.')+f'''<section class="section container about-grid"><div><h2>Our Mission</h2><p>Our mission is to help neighborhood youth develop teamwork, sportsmanship, character, and community spirit through the challenge and enjoyment of team sports.</p><p>We want young people to enjoy participating and feel proud to wear an SPYA uniform.</p></div><div class="address-panel"><h2>Our Home</h2><address>360 Grange Road<br>Allentown, PA 18069</address><p>Program locations vary. Association meetings are held at the Grange Park Fieldhouse; confirm the next meeting date with the secretary.</p></div></section><section id="contacts" class="section contact-section"><div class="container"><h2>Association Contacts</h2><p>Program questions belong with the commissioner listed on each sport’s page. These contacts handle association matters.</p><div class="contact-grid">{contacts}</div><p class="small">The treasurer also coordinates the warehouse and fieldhouse.</p>{accordion('Soccer Commissioner Opportunity','<p>SPYA’s board page lists the soccer commissioner position as vacant. Contact the president to ask about the role and its current status.</p>')}</div></section>'''
write('about.html',shell('About SPYA',body,'about'))
write('404.html',shell('Page Not Found',intro('Page Not Found','Let’s Get You Back on Track','Use the navigation above to find a program, registration information, or family resources.')))
print('Built',len(list(R.glob('*.html'))),'pages.')

# Copy refinement: one visible full organization name per page.
