from pathlib import Path
from html import escape as e
import json
R=Path(__file__).resolve().parents[1]
D=json.loads((R/'data/site.json').read_text());S=D['sports']
PHOTO='https://spya.org/wp-content/uploads/sites/1365/2023/08/358619442_231454846479417_3815966003868382360_n.jpg'
POLICY='https://spya.org/wp-content/uploads/sites/1365/2026/09/SPYA-Financial-Assistance-Policy-revised-September-2026.pdf'
APPLICATION='https://spya.org/wp-content/uploads/sites/1365/2026/07/SPYA-Financial-Assistance-Application-1.pdf'
def button(label,url,secondary=False):return f'<a class="button {"secondary" if secondary else ""}" href="{e(url)}">{e(label)}</a>'
def shell(title,body,active=''):
 items=[('sports','sports.html','Sports'),('resources','resources.html','For families'),('about','about.html','About SPYA')]
 nav=''.join(f'<a href="{u}" '+('aria-current="page" ' if active==k else '')+f'>{t}</a>' for k,u,t in items)
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>{e(title)} | South Parkland Youth Association</title><meta name="description" content="Explore South Parkland Youth Association sports, family resources and program contacts."><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><link rel="stylesheet" href="css/styles.css"><script src="js/app.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header><div class="container header-inner"><a class="brand" href="index.html" aria-label="SPYA home"><span class="monogram">SPYA<span class="brand-dot">.</span></span><span class="brand-name">South Parkland<br>Youth Association</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav">Menu</button><nav class="nav" id="primary-nav" aria-label="Main navigation">{nav}<a class="nav-button" href="registration.html" {'aria-current="page"' if active=='registration' else ''}>Registration</a></nav></div></header><main id="main">{body}</main><footer><div class="container footer-top"><div><a class="brand" href="index.html"><span class="monogram">SPYA<span class="brand-dot">.</span></span></a><p>South Parkland Youth Association<br>Allentown, Pennsylvania</p></div><nav aria-label="Footer navigation"><a href="sports.html">Sports</a><a href="resources.html">Family resources</a><a href="about.html#contacts">Contact us</a><a href="calendar.html">Schedules</a></nav></div><div class="container footer-bottom"><span>Community. Teamwork. Sportsmanship.</span><span>Website preview</span></div></footer></body></html>'''
def intro(kicker,title,text):return f'<section class="page-intro container"><div class="eyebrow">{e(kicker)}</div><h1>{e(title)}</h1><p class="lead">{e(text)}</p></section>'
def cards():return ''.join(f'<a class="sport-card" href="{s["slug"]}.html" data-sport="{e(s["name"]+" "+s["season"])}"><h2>{e(s["name"])}</h2><p>{e(s["summary"])}</p><span class="sport-arrow" aria-hidden="true">↗</span></a>' for s in S)
def write(name,body): (R/name).write_text(body,encoding='utf-8')
home=f'''<section class="home-hero container"><div class="hero-copy"><div class="eyebrow">Youth sports in Allentown</div><h1>A place to play.<br><span>A team to belong to.</span></h1><p class="lead">Discover youth sports and a community built around teamwork, sportsmanship and participation.</p>{button('Explore our sports','sports.html')}</div><figure class="hero-photo"><img src="{PHOTO}" alt="SPYA’s 2023 Senior Legion championship team" fetchpriority="high"><figcaption>South Parkland Senior Legion · 2023</figcaption></figure></section><section class="pathways container" aria-label="Get started"><a href="sports.html"><span class="eyebrow">For players</span><h2>Find their sport.</h2><span class="inline-link">Explore nine programs <span aria-hidden="true">↗</span></span></a><a href="resources.html#volunteer"><span class="eyebrow">For volunteers</span><h2>Make a difference.</h2><span class="inline-link">Get involved <span aria-hidden="true">↗</span></span></a><a href="resources.html"><span class="eyebrow">For families</span><h2>Feel prepared.</h2><span class="inline-link">Find helpful information <span aria-hidden="true">↗</span></span></a></section><section class="mission"><div class="container mission-inner"><div><div class="eyebrow">Our community</div><h2>Growing through sport.</h2></div><div><p>SPYA is a nonprofit, volunteer-run association that helps neighborhood youth develop teamwork, sportsmanship, character and community spirit through team sports.</p><a class="inline-link" href="about.html">Get to know SPYA <span aria-hidden="true">↗</span></a></div></div></section>'''
write('index.html',shell('Home',home))
write('sports.html',shell('Sports',intro('Our sports','Find their game.','Explore our programs, then choose a sport to learn more.')+f'<section class="section container"><div class="toolbar"><label for="sport-search">Search sports<input id="sport-search" type="search" data-search placeholder="Enter a sport or season"></label><span data-count aria-live="polite">9 sports</span></div><div class="sports-grid">{cards()}</div><p data-empty hidden>No matching sports. Try another search.</p></section>','sports'))
for s in S:
 details=''.join(f'<details><summary>{e(t)}</summary><p>{e(p)}</p></details>' for t,p in s['programs'])
 body=intro(s['name'],s['name'],s['summary'])+f'''<section class="section container detail-grid"><div><h2>About the program</h2><div class="programs">{details}</div><p class="small">For current eligibility, fees and schedules, contact the program commissioner.</p></div><aside class="contact-panel"><div class="eyebrow">Let’s get you started</div><h2>Have a question?</h2><p>Ask about team placement, equipment and the next season.</p><a class="email" href="mailto:{s['email']}">{s['email']}</a><a class="inline-link" href="registration.html">Registration information <span aria-hidden="true">↗</span></a></aside></section>'''
 write(s['slug']+'.html',shell(s['name'],body,'sports'))
contacts=''.join(f'<article class="contact"><h3>{e(s["name"])}</h3><a href="mailto:{s["email"]}">{s["email"]}</a></article>' for s in S)
body=intro('Registration','Start with the right program.','Your sport commissioner can confirm eligibility, available places and the registration process.')+f'''<section class="section container"><div class="steps"><div><span>01</span><h2>Choose a sport</h2><p>Explore the programs and find the right fit.</p><a class="inline-link" href="sports.html">View sports ↗</a></div><div><span>02</span><h2>Confirm the details</h2><p>Ask about fees, equipment and the weekly commitment.</p></div><div><span>03</span><h2>Register through TeamSnap</h2><p>Use the current registration link provided for your program.</p></div></div><details class="registration-contacts"><summary>Find your sport’s registration contact</summary><div class="contact-grid">{contacts}</div></details><p class="small">Need help with registration costs? <a href="resources.html#assistance">Explore financial assistance.</a></p></section>'''
registration_status = """<section class="section container"><h2>Registration forms</h2><p class="small">Status checked September 16, 2026. Closed forms are not accepting registrations.</p><div class="contact-grid"><article class="contact"><h3>NFL Flag</h3><p>Registration closed September 3, 2026.</p></article><article class="contact"><h3>Soccer</h3><p>Registration closed September 12, 2026.</p></article><article class="contact"><h3>Softball</h3><p>Registration closed September 1, 2026.</p></article><article class="contact"><h3>Cheer</h3><p>Availability is unconfirmed. TeamSnap sign-in may be required.</p><a class="button" href="https://go.teamsnap.com/forms/521215">View registration form</a></article></div></section>"""
body += registration_status
write('registration.html',shell('Registration',body,'registration'))
body=intro('For families','The essentials, in one place.','Practical guidance for joining a team and supporting your child’s season.')+f'''<section class="section container resource-sections"><article id="assistance"><div><div class="eyebrow">Financial assistance</div><h2>Support for participation.</h2></div><div><p>SPYA offers financial assistance to eligible families, subject to available funding. Contact the assistance team about the application and required documents.</p><a class="email" href="mailto:FinancialAid@spya.org">FinancialAid@spya.org</a><details><summary>Application documents</summary><p><a href="{POLICY}">Financial assistance policy (PDF)</a></p><p><a href="{APPLICATION}">Financial assistance application (PDF)</a></p></details></div></article><article id="volunteer"><div><div class="eyebrow">Volunteering</div><h2>Be part of their season.</h2></div><div><p>Ask your sport commissioner about coaching, team support, field preparation or equipment assistance.</p><a class="inline-link" href="about.html#contacts">Find a contact ↗</a></div></article><article id="policies"><div><div class="eyebrow">Common questions</div><h2>Before you begin.</h2></div><div><details><summary>How do I register?</summary><p>Start with the sport commissioner to confirm the current registration link and your child’s eligibility.</p><a href="registration.html">Registration guidance</a></details><details><summary>Are tryouts required?</summary><p>Some programs use tryouts or evaluations. Ask about the process for your child’s sport and division.</p></details><details><summary>What equipment will we need?</summary><p>Confirm the program’s equipment list before buying anything. Some programs provide or loan equipment.</p></details><details><summary>Who can explain fees and refunds?</summary><p>Your sport commissioner can confirm the applicable fees and refund terms before you register.</p></details></div></article></section>'''
write('resources.html',shell('Family resources',body,'resources'))
body=intro('About SPYA','Local teams. Shared purpose.','Helping neighborhood youth learn, participate and grow through team sports.')+f'''<section class="section container about-grid"><div><h2>Our mission</h2><p>South Parkland Youth Association is a nonprofit, volunteer-run organization based in Allentown, Pennsylvania.</p><p>Through team sports, SPYA helps young people develop teamwork, sportsmanship, character and community spirit.</p></div><div class="address-panel"><div class="eyebrow">Association address</div><address>360 Grange Road<br>Allentown, PA 18069</address><p>Practice and game locations vary by program.</p></div></section><section id="contacts" class="section contact-section"><div class="container"><h2>Contact your sport</h2><p>For team placement, equipment, schedules and registration.</p><div class="contact-grid">{contacts}</div><details><summary>Association contacts</summary><div class="contact-grid"><article class="contact"><h3>President</h3><a href="mailto:president@spya.org">president@spya.org</a></article><article class="contact"><h3>Secretary</h3><a href="mailto:secretary@spya.org">secretary@spya.org</a></article><article class="contact"><h3>Treasurer</h3><a href="mailto:treasurer@spya.org">treasurer@spya.org</a></article></div></details></div></section>'''
write('about.html',shell('About SPYA',body,'about'))
body=intro('Schedules','Plan your season.','Contact your sport commissioner for practice locations, game times and team schedule information.')+'<section class="section container narrow"><h2>Looking for your team’s schedule?</h2><p>Use your team’s communications for updates and ask your commissioner if you need help finding the right information.</p>'+button('Find your sport contact','about.html#contacts')+'</section>'
write('calendar.html',shell('Schedules',body))
write('404.html',shell('Page not found',intro('Page not found','Let’s find your way back.','Explore our sports or return to the homepage.')+'<section class="section container">'+button('Explore sports','sports.html')+'</section>'))
print('Built 16 refined pages.')
