from pathlib import Path
import json
from html import escape as e
R=Path(__file__).resolve().parents[1]
D=json.loads((R/'data/site.json').read_text())
S=D['sports']
PHOTOS={'baseball.jpg':'https://spya.org/wp-content/uploads/sites/1365/2023/08/358619442_231454846479417_3815966003868382360_n.jpg','lacrosse.jpg':'https://spya.org/wp-content/uploads/sites/1365/2021/01/girls-lax.jpg'}
def photo(name): return 'assets/images/'+name if (R/'assets/images'/name).exists() else PHOTOS[name]
def btn(label,url,kind=''): return f'<a class="btn {kind}" href="{e(url)}">{e(label)}</a>'
def shell(title,body,active=''):
 nav=''.join(f'<a href="{url}"'+(' aria-current="page"' if active==key else '')+f'>{label}</a>' for key,url,label in [('sports','sports.html','Our sports'),('calendar','calendar.html','Calendar'),('resources','resources.html','Resources'),('about','about.html','About & contact')])
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>{e(title)} · South Parkland Youth Association</title><meta name="description" content="Explore South Parkland youth sports, program information and registration resources."><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="css/styles.css"><script src="js/app.js" defer></script></head><body id="top"><a class="skip" href="#main">Skip to content</a><div class="utility"><div class="container"><span>ALLENTOWN, PA · REDESIGN PREVIEW</span><a href="https://spya.org/">Official SPYA site ↗</a></div></div><header class="site-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="South Parkland Youth Association home"><span class="brand-mark">SPYA</span><span class="brand-copy">South Parkland<br>Youth Association</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav" type="button">Menu</button><nav class="nav" id="primary-nav" aria-label="Main navigation">{nav}<a class="nav-cta" href="registration.html" {'aria-current="page"' if active=='registration' else ''}>Registration ↗</a></nav></div></header><main id="main">{body}</main><footer class="footer"><div class="container"><div class="footer-grid"><div><span class="brand-mark">SPYA</span><p>Local teams. Lasting connections.<br>Youth sports for the Parkland community.</p><p>360 Grange Road<br>Allentown, PA 18069</p></div><div><h3>Explore</h3><a href="sports.html">Our sports</a><a href="registration.html">Registration</a><a href="calendar.html">Calendar</a><a href="about.html">About & contact</a></div><div><h3>For families</h3><a href="resources.html#assistance">Financial assistance</a><a href="resources.html#volunteer">Get involved</a><a href="resources.html#policies">Policies & documents</a><a href="https://spya.org/">Official SPYA website ↗</a></div></div><div class="footer-bottom"><span>Independent redesign preview · Source reviewed {D['reviewDate']}</span><span>Confirm current program details with SPYA.</span></div></div></footer></body></html>'''
def intro(kicker,title,desc): return f'<div class="page-hero"><div class="container"><div class="breadcrumb"><a href="index.html">Home</a> / {e(kicker)}</div><div class="eyebrow">{e(kicker)}</div><h1>{e(title)}</h1><p class="lead">{e(desc)}</p></div></div>'
def cards():
 return ''.join(f'<a class="sport-card" href="{s["slug"]}.html" data-sport="{e(s["name"]+" "+s["season"])}"><div class="card-top"><span class="sport-no">{i:02}</span><span class="season">{e(s["season"])}</span></div><h3>{e(s["name"])}</h3><p>{e(s["summary"])}</p><div class="card-foot">Explore program <span aria-hidden="true">↗</span></div></a>' for i,s in enumerate(S,1))
def write(name,body): (R/name).write_text(body,encoding='utf-8')
home=f'''<div class="hero"><div class="container hero-grid"><div class="hero-copy"><div class="eyebrow">South Parkland Youth Association</div><h1>Big dreams.<br>Local teams.<br><span>One community.</span></h1><p class="lead">A first practice. A new friendship. A team to call your own. Find where your child's next chapter begins.</p><div class="actions">{btn('Find your sport','sports.html')}{btn('Registration information','registration.html','outline')}</div></div><div class="hero-art"><span class="hero-fallback">PLAY.<br>GROW.<br>BELONG.</span><img src="{photo('baseball.jpg')}" alt="Baseball team photograph published by SPYA" fetchpriority="high"><span class="hero-word" aria-hidden="true">PARKLAND</span><div class="photo-label"><small>More than the final score</small><strong>Confidence starts<br>with showing up.</strong></div></div></div></div><div class="container quick-strip"><a href="sports.html"><span class="quick-icon">01</span><div><small>Find your fit</small><strong>Explore nine sports</strong></div></a><a href="registration.html"><span class="quick-icon">02</span><div><small>Plan your season</small><strong>Registration & next steps</strong></div></a><a href="about.html#contacts"><span class="quick-icon">03</span><div><small>We're here to help</small><strong>Find your commissioner</strong></div></a></div><section class="section soft"><div class="container"><div class="section-head"><div><div class="eyebrow">Something for every player</div><h2>Find their game.</h2></div><p>First-timers and experienced players. Different sports, one shared sense of belonging.</p></div><div class="sports-grid">{cards()}</div></div></section><section class="section"><div class="container feature-grid"><img class="feature-photo" src="{photo('lacrosse.jpg')}" alt="Lacrosse photograph from SPYA's program page" loading="lazy"><div class="feature-copy"><div class="eyebrow">Built by our community</div><h2>Good teammates.<br>Great beginnings.</h2><p>SPYA is a volunteer-run organization helping neighborhood youth develop teamwork, sportsmanship and character through sport.</p><ul class="rule-list"><li><b>01</b>Space to learn and develop skills</li><li><b>02</b>Friendships that go beyond game day</li><li><b>03</b>Parents and volunteers who make it happen</li></ul><a class="text-link" href="about.html">Get to know SPYA ↗</a></div></div></section><section class="callout"><div class="container"><h2>A little of your time.<br>A big part of their season.</h2>{btn('Get involved','resources.html#volunteer','light')}</div></section>'''
write('index.html',shell('Home',home))
body=intro('Our sports','Their next favorite sport starts here.','Explore the programs, understand the commitment and find the right person to ask.')+f'<section class="section"><div class="container"><div class="toolbar"><label for="sport-search">Find a sport or season <input id="sport-search" data-search type="search" placeholder="Try baseball or spring"></label><span class="count" data-count aria-live="polite">9 sports</span></div><div class="sports-grid">{cards()}</div><p class="empty" data-empty hidden>No matching sports. Try another sport or season.</p></div></section>'
write('sports.html',shell('Our sports',body,'sports'))
for s in S:
 programs=''.join(f'<article class="program"><h3>{e(t)}</h3><p>{e(p)}</p></article>' for t,p in s['programs'])
 links=s.get('links',[])+[('Full official '+s['name']+' information',s['source'])]
 resources=''.join(f'<a class="resource-link" href="{e(u)}">{e(t)} <span aria-hidden="true">↗</span></a>' for t,u in links)
 picture=f'<img class="detail-image" src="{photo(s["image"])}" alt="{e(s["name"])} photograph published by SPYA">' if s.get('image') else ''
 body=intro(s['name'],s['tag'],s['summary'])+f'''<section class="section"><div class="container detail-layout"><div>{picture}<div class="eyebrow">Explore the program</div><h2>Room to grow.</h2>{programs}<div class="notice"><strong>Before you register</strong>{e(s['note'])}</div><h3>Program resources</h3>{resources}<p class="source-note">Summary based on public SPYA content reviewed {D['reviewDate']}. Season labels describe published offerings, not current availability.</p></div><aside class="sidebar" aria-label="Program at a glance"><div class="eyebrow">At a glance</div><h2>{e(s['name'])}</h2><dl><dt>Published seasons</dt><dd>{e(s['season'])}</dd><dt>Who can play</dt><dd>{e(s['audience'])}</dd><dt>Time commitment</dt><dd>{e(s['commitment'])}</dd></dl>{btn('Registration guidance','registration.html')}<p style="margin-top:22px">Have a question?<br><a href="mailto:{s['email']}">{s['email']}</a></p><a href="resources.html#assistance">Financial assistance</a></aside></div></section>'''
 write(s['slug']+'.html',shell(s['name'],body,'sports'))
rows=''
for s in S:
 status='Fall closed in reviewed source' if s['slug']=='nfl-flag' else 'Confirm availability'
 rows+=f'<article class="reg-row"><div><h3>{s["name"]}</h3><p>{e(s["season"])}</p></div><div><span class="status">{status}</span><p><a href="mailto:{s["email"]}">Ask the commissioner</a></p></div>{btn("Official program page",s["source"],"dark")}</article>'
body=intro('Registration','A clear path to game day.','Choose a program, confirm the details and register through SPYA’s official system.')+f'''<section class="section"><div class="container"><div class="two-col"><div><div class="eyebrow">Before you begin</div><h2>Know your next step.</h2><ol class="rule-list"><li><b>01</b>Check your child's division, season and eligibility.</li><li><b>02</b>Confirm fees, equipment and the weekly commitment.</li><li><b>03</b>Complete the official TeamSnap registration.</li></ol></div><div class="panel"><h3>Registration happens with SPYA.</h3><p>This preview does not collect player details or payments. The official page provides registration links and financial assistance documents.</p>{btn('Open official registration','https://spya.org/registration/')}</div></div><div class="notice"><strong>Season information is being verified</strong>The source contains conflicting and expired announcements. Links below help you confirm availability; they do not indicate that places are open.</div>{rows}</div></section>'''
write('registration.html',shell('Registration',body,'registration'))
policy='https://spya.org/wp-content/uploads/sites/1365/2026/09/SPYA-Financial-Assistance-Policy-revised-September-2026.pdf'
application='https://spya.org/wp-content/uploads/sites/1365/2026/07/SPYA-Financial-Assistance-Application-1.pdf'
bylaws='https://spya.org/wp-content/uploads/sites/1365/2020/04/SPYA-BY-LAWS-06-10-2019.pdf'
body=intro('Resources','Less searching. More playing.','Practical information for parents, guardians and the volunteers behind each season.')+f'''<section class="section"><div class="container"><div class="two-col"><article class="panel" id="assistance"><div class="eyebrow">Support for families</div><h2>Financial assistance.</h2><p>SPYA offers assistance subject to demonstrated need and available funding. Review the current policy and required documentation before applying.</p><a class="resource-link" href="{policy}">Assistance policy · PDF ↗</a><a class="resource-link" href="{application}">Application form · PDF ↗</a><a class="resource-link" href="mailto:FinancialAid@spya.org">Contact the assistance team ↗</a></article><article class="panel" id="volunteer"><div class="eyebrow">Make a difference</div><h2>Be part of the team.</h2><p>Ask your sport commissioner about coaching, team support, field preparation, equipment, concessions or other ways to help.</p><p>Volunteer obligations and reimbursable fees can vary. Confirm the requirements for your program.</p>{btn('Find a commissioner','about.html#contacts','dark')}</article></div></div></section><section class="section soft" id="policies"><div class="container"><div class="section-head"><h2>Policies & answers.</h2><p>One place for shared information. Sport-specific rules remain with each program.</p></div><a class="resource-link" href="{bylaws}">Published association bylaws · 2019 PDF ↗</a><details><summary>How do I register?</summary><p>Use the official SPYA registration page after confirming your child's eligibility and the program's availability. Registration is handled through TeamSnap.</p><a href="registration.html">See registration guidance</a></details><details><summary>Can I get a refund?</summary><p>Published sport pages and bylaws describe different circumstances and exceptions. Confirm the current refund policy with the commissioner before paying.</p></details><details><summary>Does my child need to attend tryouts?</summary><p>It depends on the program. Some competitive teams require tryouts. Field Hockey describes evaluations to balance teams. Check your sport page and ask the commissioner.</p></details><details><summary>What equipment should we buy?</summary><p>Wait until you have the current program equipment list. Some programs supply or loan equipment; others require separate purchases.</p></details><details><summary>Where will practices take place?</summary><p>Locations vary by sport and team. Published examples include Grange Park and local schools. Confirm your assigned location and schedule before attending.</p></details></div></section>'''
write('resources.html',shell('Family resources',body,'resources'))
contacts=''.join(f'<article class="contact"><h3>{s["name"]}</h3><small>Program questions</small><a href="mailto:{s["email"]}">{s["email"]}</a></article>' for s in S)
body=intro('About & contact','Our community. Their future.','A volunteer-run youth sports association serving the Parkland community in and around Allentown, Pennsylvania.')+f'''<section class="section"><div class="container two-col"><div><div class="eyebrow">What brings us together</div><h2>A love of sport.<br>A sense of belonging.</h2><p class="lead">SPYA helps neighborhood youth develop teamwork, sportsmanship, character and community spirit through team sports.</p><p>Our purpose is simple: help children enjoy participating and feel proud to be part of their team.</p></div><div class="panel"><h3>Find the right person.</h3><p>For eligibility, schedules, equipment or registration, start with the relevant sport commissioner.</p><p>For association matters, consult the official board directory for current officers and responsibilities.</p>{btn('Official board directory','https://spya.org/board/','dark')}<p style="margin-top:25px"><strong>Published association address</strong><br>360 Grange Road<br>Allentown, PA 18069</p></div></div></section><section class="section soft" id="contacts"><div class="container"><div class="section-head"><h2>Let's get you connected.</h2><p>Public program contacts from the reviewed source. Check the official directory if a contact has changed.</p></div><div class="contact-list">{contacts}</div></div></section>'''
write('about.html',shell('About & contact',body,'about'))
body=intro('Calendar','Make room for game day.','Find the official calendar and confirm the schedule for your program.')+'''<section class="section"><div class="container two-col"><article class="panel"><div class="eyebrow">Association events</div><h2>The official calendar.</h2><p>The original website hosts SPYA's public calendar. Open it for published events and check the relevant sport's updates for changes.</p>'''+btn('Open SPYA calendar','https://spya.org/calendar/')+'''</article><article class="panel"><h3>Looking for a team schedule?</h3><p>Team practices, game times and last-minute changes should be confirmed through your team's communications or commissioner.</p><a class="resource-link" href="about.html#contacts">Contact your sport ↗</a><a class="resource-link" href="sports.html">Explore program information ↗</a></article></div></section>'''
write('calendar.html',shell('Calendar',body,'calendar'))
write('404.html',shell('Page not found',intro('Page not found','Let’s get you back in the game.','This page is unavailable. Explore the sports directory or return to the homepage.')+'<section class="section"><div class="container">'+btn('Explore sports','sports.html')+'</div></section>'))
print('Built',len(list(R.glob('*.html'))),'pages.')
